### ISSUE TITLE
[Docs]: Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by koralowiec** [devcontainers-extra/features#57]
We should have documentation in the form of `CONTRIBUTING.md` about adding a new feature to the repo
It should contain information about `just` commands and about testing

**Comment by pl4nty** [comment]
Thanks, happy to take this one

**Comment by koralowiec** [comment]
I merged the PR, and decided to move my question here

>  Do you think that we should a link to CONTRIBUTING.md in README? Something like "If you want to contribute, check CONTRIBUTING.md"?
> ~ https://github.com/devcontainers-extra/features/pull/59#pullrequestreview-2380265772
