### ISSUE TITLE
Chore: Run Free Disk Space step only for tests that need it

### ISSUE THREAD

**Issue by koralowiec** [devcontainers-extra/features#72]
After introducing disk cleanup in #69, it runs for each test job. As pointed out by @klezm in https://github.com/devcontainers-extra/features/pull/69#issuecomment-2454477827, it's only needed for a couple of test scenarios, so it could be limited with a conditional for them (run Free Disk Space step only when the tests for a specific feature require it)

**Comment by klezm** [comment]
The only package needing more space as I see it is `homebrew-package` for now
